version: '3'
services:

  switch2-redis:
    image: redis:5.0.12-alpine3.13
    restart: always
    expose:
      - 6379
    networks:
      - network

  switch2-rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5672
      - 15672
    labels:
      - "traefik.frontend.rule=Host:switch2-rabbitmq.tangogolf.lan"
      - "traefik.port=15672"
    networks:
      - network

  switch2-consumer-ec:
    build:
      context: ./consumer
      dockerfile: Dockerfile.execute-change
    restart: always
    networks:
      - network

  switch2-consumer-cl:
    build:
      context: ./consumer
      dockerfile: Dockerfile.control-loop
    restart: always
    networks:
      - network

  switch2-scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    restart: always
    networks:
      - network

  switch2-management:
    build:
      context: ./management
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5000
    labels:
      - "traefik.frontend.rule=Host:switch2.tangogolf.lan"
      - "traefik.port=5000"
    volumes:
      - "./json:/json"
    networks:
      - network

networks:
  network:
