FROM python:3-alpine3.13

RUN apk add --update --no-cache \
  py3-pip \
  python3

RUN pip install --no-cache-dir \
  pika \
  requests

COPY bin /consumer/bin
COPY scripts/roller-shutter.py /consumer/roller-shutter.py

CMD ["python", "/consumer/roller-shutter.py"]
