FROM python:3-alpine3.13

RUN apk add --update --no-cache \
  py3-pip \
  python3

RUN pip install --no-cache-dir \
  pika \
  requests

COPY bin /consumer/bin
COPY scripts/execute-change.py /consumer/execute-change.py

ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "/consumer/execute-change.py"]
